export const UserConstants = {
  Login: {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL",
    LOGOUT: "USER_LOGOUT",
  },
  Register: {
    REQUEST: "USER_REGISTER_REQUEST",
    SUCCESS: "USER_REGISTER_SUCCESS",
    FAIL: "USER_REGISTER_FAIL",
  },
};
