export const UserConstants = {
  Login: {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL",
    LOGOUT: "USER_LOGOUT",
  },
  Register: {
    REQUEST: "USER_REGISTER_REQUEST",
    SUCCESS: "USER_REGISTER_SUCCESS",
    FAIL: "USER_REGISTER_FAIL",
  },
  Details: {
    REQUEST: "USER_DETAILS_REQUEST",
    SUCCESS: "USER_DETAILS_SUCCESS",
    FAIL: "USER_DETAILS_FAIL",
  },
  Update: {
    REQUEST: "USER_UPDATE_REQUEST",
    SUCCESS: "USER_UPDATE_SUCCESS",
    FAIL: "USER_UPDATE_FAIL",
    RESET: "USER_UPDATE_RESET",
  },
};
